### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by andyxuq** [Appsaholic/php-sdk#1]
Hi BlakeGardner
    I downloaded your project just right now, and I tried the api method which under example directory with my own configuration as below:
$appsaholicSession = new Session(
    'OUR_APP_KEY',
    'OUR_APP_SECRE',
    'OUR_USER_ID'
);

But I get 404 response in full of four php examples under example directory, error message is shown below:
![image](https://cloud.githubusercontent.com/assets/6957227/7856842/cad1c184-055e-11e5-9959-d6c5e7c3b517.png)

Can u give me any suggestion?

**Comment by BlakeGardner** [comment]
Hey @andyxuq How are you getting the user ID? Is it the user ID of the Perk user after you've logged in? Is it a numeric ID or does it look like a UUID? e.g. `402493d2-a918-48cb-9ac9-114b12e63e35`

**Comment by andyxuq** [comment]
Hi @BlakeGardner, Yes I got a user Id and it looks like a UUID, and also I used this userId as a parameter to init Session object, but I get this userId from google play, It's Google's Advertising Id, Does this id ok? Or should I get this id from Perk System, How can I get a userId from Perk?
